baseurl                  = "https://whalerdao.org"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "WhalerDAO"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "Home"                           # What to call the home page link
    footerText           = "WhalerDAO"

# Metadata for Open Graph and Twitter
    description          = "WhalerDAO"               # Max 160 characters show in search results
    images               = []                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "WhalerDAO"
    # rss                = ""

[[params.mainMenu]]
    link = "manifesto"
    text = "The WhalerDAO Manifesto"

[imaging]
    quality = 75
